### ISSUE TITLE
Cannot connect to mysql

### ISSUE THREAD

**Issue by jackchuong** [kheeklab/privacyidea-docker#89]
Hi all,
This is my docker-compose.yml
```
version: '2.1'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.4'
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=privacyidea
      - MARIADB_USER=privacyidea
      - MARIADB_PASSWORD=privacyidea
    volumes:
      - ./mysqldata:/var/lib/mysql

  privacyidea:
    image: 'khalibre/privacyidea:v3.9-patch1'
    ports:
      - '80:80'
    environment:
      - DB_VENDOR=mariadb
      - DB_NAME=privacyidea
      - DB_HOST=mariadb
      - DB_USER=privacyidea
      - DB_PASSWORD=privacyidea
      - SECRET_KEY=suppersecretkey
      - PI_PEPPER=secretworduseforadminencrypt
      - PI_PAGE_TITLE=pivacyIDEA
    depends_on:
      - mariadb
```

This is logs from privacyidea container
```
<SQLAlchemy engine=mariadb+pymysql://privacyidea:***@mariadb:3306/privacyidea>
Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/pymysql/connections.py", line 644, in connect
    sock = socket.create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/privacyidea/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/privacyidea/lib/python3.8/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/privacyidea/lib/python3.8/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mariadb' ([Errno 111] Connection refused)")
```
I can connect to mariadb from another computer , so I think it is python or privacyidea container problem.
Please give me some advice.

**Comment by mr-ssd** [comment]
@jackchuong could you try to start mariadb service and wait for it to be ready first and then start PI service later?

**Comment by jackchuong** [comment]
@mr-ssd thank you , I wait for mariadb start successfully and then I restart privacyidea container , it worked fine.
